version: '3'
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
          - POSTGRES_USERNAME=postgres
          - POSTGRES_PASSWORD=postgres_password
        ports:
          - 5432:5432
        volumes:
          - ./postgres/docker-entrypoint-initdb:/docker-entrypoint-initdb.d
          - pg-data:/var/lib/postgresql/data
      
    pgadmin:
        container_name: pgadmin4
        image: dpage/pgadmin4
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: root@root.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - 5050:80
          
volumes:
  pg-data: